{{ $webhookserver := .Values.webhookserver }}
{{- $certSource     := .Values.tls.certSource -}}
{{- $certSecretName := "" -}}
{{- if eq $certSource "certmanager" }}
{{- $certSecretName = printf "%s-apiserver" (include "netguard-chart.fullname" .) -}}
{{- else if eq $certSource "secret" }}
{{- $certSecretName = .Values.tls.secret.apiserver.secretName -}}
{{- end }}
{{- $sa     := $webhookserver.serviceAccount -}}
{{- $saName := default (printf "%s-webhookserver" (include "netguard-chart.fullname" .)) $sa.name -}}
{{- if not $sa.create }}
{{- $saName = "default" -}}
{{- end }}

{{- if $webhookserver.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netguard-chart.fullname" . }}-webhookserver
  labels:
    app.kubernetes.io/component: webhookserver
    {{- include "netguard-chart.labels" . | nindent 4 }}
spec:
  {{- if not $webhookserver.autoscaling.enabled }}
  replicas: {{ $webhookserver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: webhookserver
      {{- include "netguard-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $webhookserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: webhookserver
        {{- include "netguard-chart.labels" . | nindent 8 }}
        {{- with $webhookserver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $webhookserver.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $saName }}
      {{- with $webhookserver.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webhookserver
          {{- with $webhookserver.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $webhookserver.image.repository }}:{{ $webhookserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $webhookserver.image.pullPolicy }}
          command:
            - /netguard-webhook
          {{- with $webhookserver.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $webhookserver.service.ports.http }}
              protocol: TCP
          {{- with $webhookserver.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $webhookserver.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $webhookserver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $webhookserver.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/netguard/config.yaml
              name: configfile
              subPath: client-config
          {{- if $certSecretName }}
            - mountPath: /etc/certs/
              name: certificate
          {{- end }}
          {{- with $webhookserver.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: configfile
          configMap:
            defaultMode: 420
            name: {{ default (printf "%s-webhookserver-config" (include "netguard-chart.fullname" .)) $webhookserver.customConfigConfigMapName }}
      {{- if $certSecretName }}
        - name: certificate
          secret:
            defaultMode: 420
            secretName: {{ $certSecretName }}
      {{- end }}
      {{- with $webhookserver.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $webhookserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $webhookserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $webhookserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $webhookserver.priorityClassName }}
      priorityClassName: "{{ $webhookserver.priorityClassName }}"
      {{- end }}
{{- end }}
