{{- if .Values.webhookserver.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "netguard-chart.fullname" . }}-webhookserver
  labels:
    app.kubernetes.io/component: webhookserver
    {{- include "netguard-chart.labels" . | nindent 4 }}
{{- if eq .Values.tls.certSource "certmanager" }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/{{ include "netguard-chart.fullname" . }}-webhookserver"
{{- end }}
webhooks:
  - name: service.netguard.sgroups.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: "{{ include "netguard-chart.fullname" . }}-webhookserver"
        namespace: {{ $.Release.Namespace }}
        path: /mutate
        port: {{ .Values.webhookserver.service.ports.http }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - netguard.sgroups.io
        apiVersions:
          - v1beta1
        resources:
          - services
          - addressgroups
          - addressgroupbindings
          - addressgroupportmappings
          - rules2s
          - servicealiases
          - addressgroupbindingpolicies
          - ieagagrules
          - hostbindings
          - svcsvcrules
          - networkbindings
          - svcfqdnrules
          - iecidrsvrules
        scope: Namespaced
    failurePolicy: Fail
    sideEffects: None
    namespaceSelector: {}
    timeoutSeconds: 10
{{- end }}
