apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netguard-chart.fullname" . }}-apiserver
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "netguard-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiserver.autoscaling.enabled }}
  replicas: {{ .Values.apiserver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
      {{- include "netguard-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: apiserver
        {{- include "netguard-chart.labels" . | nindent 8 }}
        {{- with .Values.apiserver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.apiserver.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netguard-chart.serviceAccountName" . }}-apiserver
      {{- with .Values.apiserver.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: apiserver
          {{- with .Values.apiserver.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.apiserver.image.repository }}:{{ .Values.apiserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiserver.service.port }}
              protocol: TCP
          {{- with .Values.apiserver.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiserver.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiserver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiserver.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.apiserver.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.apiserver.priorityClassName }}
      priorityClassName: "{{ .Values.apiserver.priorityClassName }}"
      {{- end }}
