{{- $apiServer      := .Values.apiserver -}}
{{- $certSource     := .Values.tls.certSource -}}
{{- $certSecretName := "" -}}
{{- if eq $certSource "certmanager" }}
{{- $certSecretName = printf "%s-apiserver" (include "netguard-chart.fullname" .) -}}
{{- else if eq $certSource "secret" }}
{{- $certSecretName = .Values.tls.secret.apiserver.secretName -}}
{{- end }}
{{- $configTLS      := (dig "authn" "tls" (dict) $apiServer.config) -}}
{{- $certFile       := (dig "cert-file" "/opt/h-bf/netguard/tls/tls.crt" $configTLS) -}}
{{- $keyFile        := (dig "key-file" "/opt/h-bf/netguard/tls/tls.key" $configTLS) -}}
{{- $clientCa       := (dig "client" "ca-files" "/opt/h-bf/netguard/tls/ca.crt" $configTLS) -}}
{{- $sa             := $apiServer.serviceAccount -}}
{{- $saName         := default (printf "%s-apiserver" (include "netguard-chart.fullname" .)) $sa.name -}}
{{- if not $sa.create }}
{{- $saName         = "default" -}}
{{- end }}

{{- if $apiServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netguard-chart.fullname" . }}-apiserver
  labels:
    app.kubernetes.io/component: apiserver
    {{- include "netguard-chart.labels" . | nindent 4 }}
spec:
  {{- if not $apiServer.autoscaling.enabled }}
  replicas: {{ $apiServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
      {{- include "netguard-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $apiServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: apiserver
        {{- include "netguard-chart.labels" . | nindent 8 }}
        {{- with $apiServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $apiServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $saName }}
      {{- with $apiServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: apiserver
          {{- with $apiServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $apiServer.image.repository }}:{{ $apiServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $apiServer.image.pullPolicy }}
          command:
            - /netguard-apiserver
          args:
            - --config=/etc/netguard/config.yaml
          {{ with $apiServer.extraArgs }}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $apiServer.service.ports.http }}
              protocol: TCP
          {{- with $apiServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $apiServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $apiServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/netguard/config.yaml
              name: configfile
              subPath: config
          {{- if $certSecretName }}
            - mountPath: {{ $certFile | quote }}
              name: certificate
              subPath: tls.crt
            - mountPath: {{ $keyFile | quote }}
              name: certificate
              subPath: tls.key
            - mountPath: {{ $clientCa | quote }}
              name: certificate
              subPath: ca.crt
          {{- end }}
          {{- with $apiServer.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: configfile
          configMap:
            defaultMode: 420
            name: {{ default (printf "%s-apiserver-config" (include "netguard-chart.fullname" .)) $apiServer.customConfigConfigMapName }}
      {{- if $certSecretName }}
        - name: certificate
          secret:
            defaultMode: 420
            secretName: {{ $certSecretName }}
      {{- end }}
      {{- with $apiServer.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $apiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $apiServer.priorityClassName }}
      priorityClassName: "{{ $apiServer.priorityClassName }}"
      {{- end }}
{{- end }}
