{{- $backend        := .Values.backend -}}
{{- $migration      := $backend.migrationContainer -}}
{{- $certSource     := .Values.tls.certSource -}}
{{- $certSecretName := "" -}}
{{- if eq $certSource "certmanager" }}
{{- $certSecretName = printf "%s-backend" (include "netguard-chart.fullname" .) -}}
{{- else if eq $certSource "secret" }}
{{- $certSecretName = .Values.tls.secret.backend.secretName -}}
{{- end }}
{{- $configTLS      := (dig "authn" "tls" (dict) $backend.config) -}}
{{- $certFile       := (dig "cert-file" "/opt/h-bf/netguard/tls/tls.crt" $configTLS) -}}
{{- $keyFile        := (dig "key-file" "/opt/h-bf/netguard/tls/tls.key" $configTLS) -}}
{{- $clientCa       := (dig "client" "ca-files" "/opt/h-bf/netguard/tls/ca.crt" $configTLS) -}}
{{- $sa     := $backend.serviceAccount -}}
{{- $saName := default (printf "%s-backend" (include "netguard-chart.fullname" .)) $sa.name -}}
{{- if not $sa.create }}
{{- $saName = "default" -}}
{{- end }}

{{- if $backend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netguard-chart.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "netguard-chart.labels" . | nindent 4 }}
spec:
  {{- if not $backend.autoscaling.enabled }}
  replicas: {{ $backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "netguard-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: backend
        {{- include "netguard-chart.labels" . | nindent 8 }}
        {{- with $backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $saName }}
      {{- with $backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          {{- with $backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $backend.image.repository }}:{{ $backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $backend.image.pullPolicy }}
          command:
            - /server
          args:
            - --config=/etc/netguard/config.yaml
            - --pg-uri=$(DATABASE_CONNECTION_URL)
            {{ with $backend.extraArgs }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef: 
                name: "{{ include "netguard-chart.fullname" . }}-database"
          ports:
            - name: http
              containerPort: {{ $backend.service.ports.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ $backend.service.ports.grpc }}
              protocol: TCP
          {{- with $backend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $backend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/netguard/config.yaml
              name: configfile
              subPath: client-config
            {{- if $certSecretName }}
            - mountPath: {{ $certFile | quote }}
              name: certificate
              subPath: tls.crt
            - mountPath: {{ $keyFile | quote }}
              name: certificate
              subPath: tls.key
            - mountPath: {{ $clientCa | quote }}
              name: certificate
              subPath: ca.crt
            {{- end }}
            {{- with $backend.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      initContainers:
        - name: goose
          {{- with $migration.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $migration.image.repository }}:{{ $migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $migration.image.pullPolicy }}
          {{- with $migration.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef: 
                name: "{{ include "netguard-chart.fullname" . }}-database"
          {{- with $migration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: configfile
          configMap:
            defaultMode: 420
            name: {{ default (printf "%s-backend-config" (include "netguard-chart.fullname" .)) $backend.customConfigConfigMapName }}
        {{- if $certSecretName }}
        - name: certificate
          secret:
            defaultMode: 420
            secretName: {{ $certSecretName }}
        {{- end }}
        {{- with $backend.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $backend.priorityClassName }}
      priorityClassName: "{{ $backend.priorityClassName }}"
      {{- end }}
{{- end }}
