{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netguard-chart.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "netguard-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.backend.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/component: backend
    {{- include "netguard-chart.selectorLabels" . | nindent 4 }}
{{- end }}
