{{ if .Values.webResources.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-netguard.sgroups.io.v1beta1.services
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex  
          data:
            align: center
            direction: row
            gap: 6
            id: resource-badge-link-row
          children:
          - type: ResourceBadge
            data:
              id: example-resource-badge
              value: "{reqsJsonPath[0]['.kind']['-']}"
          - type: antdLink
            data:
              href: /openapi-ui/{2}/{reqsJsonPath[0]['.metadata.namespace']['-']}/factory/hbf-service-details/netguard.sgroups.io/v1beta1/services/{reqsJsonPath[0]['.metadata.name']['-']}
              id: meta-name-value
              text: "{reqsJsonPath[0]['.metadata.name']['-']}"

    - jsonPath: .metadata.namespace
      name: Namespace
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex  
          data:
            align: center
            direction: row
            gap: 6
            id: resource-badge-link-row
          children:
          - type: ResourceBadge
            data:
              id: example-resource-badge
              value: Namespace
          - type: antdLink
            data:
              href: /openapi-ui/{2}/factory/namespace-details/v1/namespaces/{reqsJsonPath[0]['.metadata.namespace']['-']}
              id: name-link
            {{ if .Values.webResources.displayNamespaceAlias }}
              text: |
                {reqsJsonPath[0]['.additionalReqsData.0.items[?(@.metadata.name=="{reqsJsonPath[0][".metadata.namespace"]}")].metadata.labels.alias']['-']}
            {{ else }}
              text: "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            {{ end }}

    - jsonPath: ".xAggregatedAddressGroups[*].name"
      name: AGs
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: OwnerRefs
            data:
              id: refs
              baseprefix: /openapi-ui
              cluster: '{2}'
              # forcedNamespace: '{3}'
              reqIndex: 0
              jsonPathToArrayOfRefs: ".xAggregatedAddressGroups[*].ref"

              errorText: error getting refs
              notArrayErrorText: refs on path are not arr
              emptyArrayErrorText: "-"
              isNotRefsArrayErrorText: objects in arr are not refs

              baseFactoryClusterSceopedAPIKey: base-factory-clusterscoped-api
              baseFactoryClusterSceopedBuiltinKey: base-factory-clusterscoped-builtin
              baseFactoryNamespacedAPIKey: base-factory-namespaced-api
              baseFactoryNamespacedBuiltinKey: base-factory-namespaced-builtin
              baseNamespaceFactoryKey: namespace-details
              baseNavigationPlural: navigations
              baseNavigationName: navigation-hbf-netguard

    - jsonPath: .spec.ingressPorts[?(@.protocol=="TCP")].port
      name: TCP In
      type: array

    - jsonPath: .spec.ingressPorts[?(@.protocol=="UDP")].port
      name: UDP In
      type: array

    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: bool

    - name: Description
      jsonPath: .spec.description
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: parsedText
            data:
              id: name-postfix
              text: '{reqsJsonPath[0][".spec.description"]["-"]}'
              style:
                display: block
                width: "300px"
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 63
    - key: Description
      value: 63
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Namespace
      value: "-"
    - key: Description
      value: "-"
    - key: TCP In
      value: "-"
    - key: UDP In
      value: "-"
    - key: Trace
      value: "-"
    - key: Logs
      value: "-"
    - key: Ready
      value: "-"
  id: stock-cluster-/netguard.sgroups.io/v1beta1/services

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-namespace-netguard.sgroups.io.v1beta1.services
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex  
          data:
            align: center
            direction: row
            gap: 6
            id: resource-badge-link-row
          children:
          - type: ResourceBadge
            data:
              id: example-resource-badge
              value: "{reqsJsonPath[0]['.kind']['-']}"
          - type: antdLink
            data:
              href: /openapi-ui/{2}/{reqsJsonPath[0]['.metadata.namespace']['-']}/factory/hbf-service-details/netguard.sgroups.io/v1beta1/services/{reqsJsonPath[0]['.metadata.name']['-']}
              id: meta-name-value
              text: "{reqsJsonPath[0]['.metadata.name']['-']}"

    - jsonPath: ".xAggregatedAddressGroups[*].name"
      name: AGs
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: OwnerRefs
            data:
              id: refs
              baseprefix: /openapi-ui
              cluster: '{2}'
              forcedNamespace: '{3}'
              reqIndex: 0
              jsonPathToArrayOfRefs: ".xAggregatedAddressGroups[*].ref"

              errorText: error getting refs
              notArrayErrorText: refs on path are not arr
              emptyArrayErrorText: "-"
              isNotRefsArrayErrorText: objects in arr are not refs

              baseFactoryClusterSceopedAPIKey: base-factory-clusterscoped-api
              baseFactoryClusterSceopedBuiltinKey: base-factory-clusterscoped-builtin
              baseFactoryNamespacedAPIKey: base-factory-namespaced-api
              baseFactoryNamespacedBuiltinKey: base-factory-namespaced-builtin
              baseNamespaceFactoryKey: namespace-details
              baseNavigationPlural: navigations
              baseNavigationName: navigation-hbf-netguard

    - jsonPath: .spec.ingressPorts[?(@.protocol=="TCP")].port
      name: TCP In
      type: array

    - jsonPath: .spec.ingressPorts[?(@.protocol=="UDP")].port
      name: UDP In
      type: array

    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: bool

    - name: Description
      jsonPath: .spec.description
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: parsedText
            data:
              id: name-postfix
              text: '{reqsJsonPath[0][".spec.description"]["-"]}'
              style:
                display: block
                width: "300px"
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 63
    - key: Description
      value: 63
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Namespace
      value: "-"
    - key: Description
      value: "-"
    - key: TCP In
      value: "-"
    - key: UDP In
      value: "-"
    - key: Trace
      value: "-"
    - key: Logs
      value: "-"
    - key: Ready
      value: "-"
  id: stock-namespace-/netguard.sgroups.io/v1beta1/services

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-project-netguard.sgroups.io.v1beta1.services
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex  
          data:
            align: center
            direction: row
            gap: 6
            id: resource-badge-link-row
          children:
          - type: ResourceBadge
            data:
              id: example-resource-badge
              value: "{reqsJsonPath[0]['.kind']['-']}"
          - type: antdLink
            data:
              href: /openapi-ui/{2}/{reqsJsonPath[0]['.metadata.namespace']['-']}/factory/hbf-service-details/netguard.sgroups.io/v1beta1/services/{reqsJsonPath[0]['.metadata.name']['-']}
              id: meta-name-value
              text: "{reqsJsonPath[0]['.metadata.name']['-']}"

    - jsonPath: ".xAggregatedAddressGroups[*].name"
      name: AGs
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: OwnerRefs
            data:
              id: refs
              baseprefix: /openapi-ui
              cluster: '{2}'
              forcedNamespace: '{3}'
              reqIndex: 0
              jsonPathToArrayOfRefs: ".xAggregatedAddressGroups[*].ref"

              errorText: error getting refs
              notArrayErrorText: refs on path are not arr
              emptyArrayErrorText: "-"
              isNotRefsArrayErrorText: objects in arr are not refs

              baseFactoryClusterSceopedAPIKey: base-factory-clusterscoped-api
              baseFactoryClusterSceopedBuiltinKey: base-factory-clusterscoped-builtin
              baseFactoryNamespacedAPIKey: base-factory-namespaced-api
              baseFactoryNamespacedBuiltinKey: base-factory-namespaced-builtin
              baseNamespaceFactoryKey: namespace-details
              baseNavigationPlural: navigations
              baseNavigationName: navigation-hbf-netguard

    - jsonPath: .spec.ingressPorts[?(@.protocol=="TCP")].port
      name: TCP In
      type: array

    - jsonPath: .spec.ingressPorts[?(@.protocol=="UDP")].port
      name: UDP In
      type: array

    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: bool

    - name: Description
      jsonPath: .spec.description
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: parsedText
            data:
              id: name-postfix
              text: '{reqsJsonPath[0][".spec.description"]["-"]}'
              style:
                display: block
                width: "300px"
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 63
    - key: Description
      value: 63
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Namespace
      value: "-"
    - key: Description
      value: "-"
    - key: TCP In
      value: "-"
    - key: UDP In
      value: "-"
    - key: Trace
      value: "-"
    - key: Logs
      value: "-"
    - key: Ready
      value: "-"
  id: stock-project-/netguard.sgroups.io/v1beta1/services

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-instance-netguard.sgroups.io.v1beta1.services
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        - type: antdFlex  
          data:
            align: center
            direction: row
            gap: 6
            id: resource-badge-link-row
          children:
          - type: ResourceBadge
            data:
              id: example-resource-badge
              value: "{reqsJsonPath[0]['.kind']['-']}"
          - type: antdLink
            data:
              href: /openapi-ui/{2}/{reqsJsonPath[0]['.metadata.namespace']['-']}/{4}/factory/hbf-service-instance-details/netguard.sgroups.io/v1beta1/services/{reqsJsonPath[0]['.metadata.name']['-']}
              id: meta-name-value
              text: "{reqsJsonPath[0]['.metadata.name']['-']}"

    - jsonPath: ".xAggregatedAddressGroups[*].name"
      name: AGs
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: OwnerRefs
            data:
              id: refs
              baseprefix: /openapi-ui
              cluster: '{2}'
              forcedNamespace: '{3}'
              reqIndex: 0
              jsonPathToArrayOfRefs: ".xAggregatedAddressGroups[*].ref"

              errorText: error getting refs
              notArrayErrorText: refs on path are not arr
              emptyArrayErrorText: "-"
              isNotRefsArrayErrorText: objects in arr are not refs

              baseFactoryClusterSceopedAPIKey: base-factory-clusterscoped-api
              baseFactoryClusterSceopedBuiltinKey: base-factory-clusterscoped-builtin
              baseFactoryNamespacedAPIKey: base-factory-namespaced-api
              baseFactoryNamespacedBuiltinKey: base-factory-namespaced-builtin
              baseNamespaceFactoryKey: namespace-details
              baseNavigationPlural: navigations
              baseNavigationName: navigation-hbf-netguard

    - jsonPath: .spec.ingressPorts[?(@.protocol=="TCP")].port
      name: TCP In
      type: array

    - jsonPath: .spec.ingressPorts[?(@.protocol=="UDP")].port
      name: UDP In
      type: array

    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: bool
  
    - name: Description
      jsonPath: .spec.description
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: parsedText
            data:
              id: name-postfix
              text: '{reqsJsonPath[0][".spec.description"]["-"]}'
              style:
                display: block
                width: "300px"
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 63
    - key: Description
      value: 63
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Namespace
      value: "-"
    - key: Description
      value: "-"
    - key: TCP In
      value: "-"
    - key: UDP In
      value: "-"
    - key: Trace
      value: "-"
    - key: Logs
      value: "-"
    - key: Ready
      value: "-"
  id: stock-instance-/netguard.sgroups.io/v1beta1/services
{{ end }}
