{{ if .Values.webResources.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomFormsOverride
metadata:
  name: netguard.sgroups.io.v1beta1.services
spec:
  hidden:
    - - apiVersion
    - - kind
    - - status
    - - xAggregatedAddressGroups
    - - networks
    - - metadata
      - creationTimestamp
    - - metadata
      - deletionGracePeriodSeconds
    - - metadata
      - deletionTimestamp
    - - metadata
      - finalizers
    - - metadata
      - generateName
    - - metadata
      - generation
    - - metadata
      - managedFields
    - - metadata
      - labels
    - - metadata
      - annotations
    - - metadata
      - ownerReferences
    - - metadata
      - resourceVersion
    - - metadata
      - selfLink
    - - metadata
      - uid
    - - spec
      - addressGroups
    - - xSvcSvcRules
    - - xSvcFqdnRules

  customizationId: default-/netguard.sgroups.io/v1beta1/services
  schema:
    properties:
      metadata:
        properties:
          namespace:
            customProps:
              keysToLabel:
                {{ .Values.webResources.namespaceSelectorLabelPath | toYaml | nindent 16 }}
              keysToValue:
                - metadata
                - name
              valueUri: "{{ .Values.webResources.namespaceValueUri }}"
            type: listInput
        type: object
      spec:
        properties:
          addressGroups:
            type: array
            items:
              type: object
              properties:
                name:
                  type: listInput
                  customProps:
                    keysToLabel:
                      - metadata
                      - name
                    keysToValue:
                      - metadata
                      - name
                    mode: tag
                    valueUri: "/api/clusters/{cluster}/k8s/apis/netguard.sgroups.io/v1beta1/namespaces/{relatedFieldValue}/addressgroups"
                    relatedValuePath: ./namespace

                namespace:
                  type: listInput
                  customProps:
                    keysToLabel:
                      - metadata
                      - name
                    keysToValue:
                      - metadata
                      - name
                    mode: tag
                    valueUri: "/api/clusters/{cluster}/k8s/api/v1/namespaces"

  strategy: merge
{{ end }}
